services:
  - type: web
    runtime: python
    plan: starter
    name: telegram-webhook
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
